services:

# PostgreSQL (pgvector)
  pgvector:
    image: pgvector/pgvector:0.8.7-pg18-trixie
    container_name: pgvector
    ports:
      - "5433:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql
    env_file:
      - ./envv/.env.postgres
    networks:
      - bakend
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  # PostgreSQL Exporter
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.20.1
    container_name: postgres-exporter
    ports:
      - "9187:9187"
    env_files:
      - ./envv/.env.postgresexporter
    depends_on:
      - pgvector
    restart: always





networks:
  bakend:
volumes:
  pgvector_data:
